#!/usr/bin/env python3
import argparse
import os
import sys
import time
from typing import List, Optional


def _run_module_main(module, argv: List[str]) -> None:
    old_argv = sys.argv
    try:
        sys.argv = argv
        module.main()
    finally:
        sys.argv = old_argv


def _add_if(args: List[str], flag: str, value) -> None:
    if value is None:
        return
    if value == "":
        return
    args.extend([flag, str(value)])


def _login_selenium(args) -> None:
    from keepliver import ctyun_auto_selenium as mod

    argv = ["ctyun_auto_selenium.py"]
    _add_if(argv, "--profile-dir", args.profile_dir)
    _add_if(argv, "--chromedriver", args.chromedriver)
    _add_if(argv, "--chrome-binary", args.chrome_binary)
    _add_if(argv, "--edgedriver", args.edgedriver)
    _add_if(argv, "--edge-binary", args.edge_binary)
    _add_if(argv, "--browser", args.browser)
    _add_if(argv, "--timeout", args.timeout)
    _add_if(argv, "--out", args.config)
    _add_if(argv, "--login-mode", args.login_mode)
    _add_if(argv, "--account", args.account)
    _add_if(argv, "--password", args.password)
    _add_if(argv, "--secrets", args.secrets)
    _add_if(argv, "--captcha-mode", args.captcha_mode)
    _add_if(argv, "--captcha-timeout", args.captcha_timeout)
    _add_if(argv, "--captcha-port", args.captcha_port)
    _add_if(argv, "--phone-verify-template", args.phone_verify_template)
    _add_if(argv, "--telegram-token", args.telegram_token)
    _add_if(argv, "--telegram-chat-id", args.telegram_chat_id)
    _add_if(argv, "--telegram-timeout", args.telegram_timeout)
    if args.telegram_test:
        argv.append("--telegram-test")
    if args.headless:
        argv.append("--headless")
    if args.force_headless:
        argv.append("--force-headless")
    if args.auto_connect:
        argv.append("--auto-connect")

    _run_module_main(mod, argv)


def _login_playwright(args) -> None:
    from keepliver import ctyun_auto as mod

    argv = ["ctyun_auto.py"]
    _add_if(argv, "--profile-dir", args.profile_dir)
    _add_if(argv, "--timeout", args.timeout)
    _add_if(argv, "--out", args.config)
    if args.headless:
        argv.append("--headless")
    _run_module_main(mod, argv)


def _run_login(args) -> None:
    if args.backend == "playwright":
        _login_playwright(args)
    else:
        _login_selenium(args)


def _load_config(path: str) -> Optional[dict]:
    try:
        from keepliver.keepalive import load_config, validate_config

        cfg = load_config(path)
        validate_config(cfg)
        return cfg
    except Exception:
        return None


def _ensure_config(path: str, args) -> dict:
    cfg = _load_config(path)
    if cfg is not None:
        return cfg

    print(f"config not found or invalid, login to generate: {path}")
    _run_login(args)
    cfg = _load_config(path)
    if cfg is None:
        raise SystemExit("login finished but config is still invalid")
    return cfg


def main() -> None:
    parser = argparse.ArgumentParser(description="Auto keepalive with login refresh.")
    parser.add_argument(
        "--config",
        default="keepliver/config.json",
        help="Path to config.json generated by login.",
    )
    parser.add_argument(
        "--interval",
        type=int,
        default=1800,
        help="Seconds between keepalive requests (default 1800 = 30 min).",
    )

    parser.add_argument(
        "--backend",
        choices=["selenium", "playwright"],
        default="selenium",
        help="Browser automation backend for login.",
    )
    parser.add_argument(
        "--profile-dir",
        default=None,
        help="Persistent browser profile dir (keeps login).",
    )
    parser.add_argument("--timeout", type=int, default=600, help="Login wait timeout.")
    parser.add_argument("--chromedriver", default=None)
    parser.add_argument("--chrome-binary", default="")
    parser.add_argument("--edgedriver", default=None)
    parser.add_argument("--edge-binary", default="")
    parser.add_argument(
        "--browser",
        choices=["chrome", "edge"],
        default="chrome",
        help="Browser type for selenium.",
    )
    parser.add_argument("--auto-connect", action="store_true")
    parser.add_argument("--login-mode", choices=["qr", "account"], default="qr")
    parser.add_argument("--account", default="")
    parser.add_argument("--password", default="")
    parser.add_argument("--secrets", default="")
    parser.add_argument(
        "--headless",
        action="store_true",
        help="Headless mode (selenium: after first login; playwright: always).",
    )
    parser.add_argument("--force-headless", action="store_true")
    parser.add_argument(
        "--captcha-mode",
        choices=["auto", "manual", "off"],
        default="auto",
    )
    parser.add_argument("--captcha-timeout", type=int, default=120)
    parser.add_argument("--captcha-port", type=int, default=8000)
    parser.add_argument(
        "--phone-verify-template",
        default=os.path.join(os.path.dirname(__file__), "login-phone-verify.html"),
    )
    parser.add_argument("--telegram-token", default="")
    parser.add_argument("--telegram-chat-id", default="")
    parser.add_argument("--telegram-timeout", type=int, default=None)
    parser.add_argument("--telegram-test", action="store_true")

    args = parser.parse_args()
    if not args.profile_dir:
        if args.backend == "playwright":
            args.profile_dir = os.path.join(os.path.dirname(__file__), ".pw-profile")
        else:
            args.profile_dir = os.path.join(os.path.dirname(__file__), ".selenium-profile")
    if not args.chromedriver:
        repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
        candidates = [
            os.path.join(os.path.dirname(__file__), "chromedriver.exe"),
            os.path.join(repo_root, "chromedriver.exe"),
            os.path.join(repo_root, "drivers", "chromedriver.exe"),
        ]
        args.chromedriver = next((p for p in candidates if os.path.exists(p)), "chromedriver")
    if not args.edgedriver:
        repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
        candidates = [
            os.path.join(os.path.dirname(__file__), "msedgedriver.exe"),
            os.path.join(repo_root, "msedgedriver.exe"),
            os.path.join(repo_root, "drivers", "msedgedriver.exe"),
        ]
        args.edgedriver = next((p for p in candidates if os.path.exists(p)), "msedgedriver")

    from keepliver import keepalive

    cfg = _ensure_config(args.config, args)

    while True:
        ok, status, payload = keepalive.send_keepalive_once(cfg)
        print("status:", status, "response:", payload)
        if not ok:
            print("keepalive failed, re-login and retry once...")
            _run_login(args)
            cfg = _ensure_config(args.config, args)
            ok2, status2, payload2 = keepalive.send_keepalive_once(cfg)
            print("status:", status2, "response:", payload2)
        time.sleep(args.interval)


if __name__ == "__main__":
    main()
