#!/usr/bin/env python3
import argparse
import hashlib
import json
import time
from typing import Dict

import requests


def build_signature(
    device_type: str,
    request_id: str,
    tenant_id: str,
    timestamp: str,
    user_id: str,
    version: str,
    secret_key: str,
) -> str:
    signature_str = (
        device_type + request_id + tenant_id + timestamp + user_id + version + secret_key
    )
    return hashlib.md5(signature_str.encode("utf-8")).hexdigest().upper()


def load_config(path: str) -> Dict:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def main():
    parser = argparse.ArgumentParser(description="CTYUN keepalive using captured config.")
    parser.add_argument(
        "--config",
        default="keepliver/config.json",
        help="Path to config.json generated by ctyun_auto.py",
    )
    parser.add_argument(
        "--interval",
        type=int,
        default=1800,
        help="Seconds between keepalive requests (default 1800 = 30 min).",
    )
    parser.add_argument(
        "--once",
        action="store_true",
        help="Send one request and exit.",
    )
    args = parser.parse_args()

    cfg = load_config(args.config)

    connect_url = cfg.get("connect_url") or "https://desk.ctyun.cn:8810/api/desktop/client/connect"
    device_info = cfg.get("device_info") or {}
    ctg_headers = {k.lower(): v for k, v in (cfg.get("ctg_headers") or {}).items()}
    auth = cfg.get("auth") or {}

    device_type_value = str(ctg_headers.get("ctg-devicetype", "60"))
    tenant_id_value = str(auth.get("tenantId") or ctg_headers.get("ctg-tenantid", ""))
    userid_value = str(auth.get("userId") or ctg_headers.get("ctg-userid", ""))
    version_value = str(ctg_headers.get("ctg-version", ""))
    secret_key_value = str(auth.get("secretKey", ""))

    if not (tenant_id_value and userid_value and version_value and secret_key_value):
        raise SystemExit("Missing auth/ctg values in config.json")

    base_headers = {
        "accept": "application/json, text/plain, */*",
        "accept-language": "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7",
        "content-type": "application/x-www-form-urlencoded",
        "ctg-appmodel": ctg_headers.get("ctg-appmodel", "2"),
        "ctg-devicecode": ctg_headers.get("ctg-devicecode", ""),
        "ctg-devicetype": device_type_value,
        "ctg-tenantid": tenant_id_value,
        "ctg-userid": userid_value,
        "ctg-version": version_value,
        "origin": "https://pc.ctyun.cn",
        "referer": "https://pc.ctyun.cn/",
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36",
    }

    # Optional headers if present
    for k in ("ctg-nego-ekeyid", "ctg-reqdata-etype"):
        if k in ctg_headers:
            base_headers[k] = ctg_headers[k]

    def send_once():
        request_id_value = str(int(time.time() * 1000))
        timestamp_value = str(int(time.time() * 1000))
        signature = build_signature(
            device_type_value,
            request_id_value,
            tenant_id_value,
            timestamp_value,
            userid_value,
            version_value,
            secret_key_value,
        )
        headers = dict(base_headers)
        headers["ctg-requestid"] = request_id_value
        headers["ctg-timestamp"] = timestamp_value
        headers["ctg-signaturestr"] = signature

        resp = requests.post(connect_url, data=device_info, headers=headers, timeout=20)
        try:
            payload = resp.json()
        except Exception:
            payload = resp.text
        print("status:", resp.status_code, "response:", payload)

    if args.once:
        send_once()
        return

    while True:
        send_once()
        time.sleep(args.interval)


if __name__ == "__main__":
    main()
